const LEVEL_INTROS: Record<number, string[]> = {
  1: [
    'You stand before the entrance to the dungeon.',
    '',
    'A cold wind rises from the stone stairway.',
    'Somewhere below, something enormous moves.',
    '',
    'You light your torch and descend.',
    '',
    'ENTERING LEVEL 1:',
    'THE UPPER PASSAGES',
    '',
    'PRESS ANY KEY',
  ],
  2: [
    'ENTERING LEVEL 2:',
    'THE FESTERING WARRENS',
    '',
    'The air is damp and foul.',
    '',
    'Patches of mold cling to the walls, and',
    'something has dragged bones across the floor.',
    '',
    'You hear goblins whispering in the darkness.',
    '',
    'PRESS ANY KEY',
  ],
  3: [
    'ENTERING LEVEL 3:',
    'THE CRYPTS OF THE RESTLESS',
    '',
    'The temperature falls as you descend.',
    '',
    'Ancient burial chambers line the passages.',
    'Their stone doors have been opened from within.',
    '',
    'PRESS ANY KEY',
  ],
  4: [
    'ENTERING LEVEL 4:',
    'THE CAVERNS OF TEETH',
    '',
    'The worked stone gives way to a vast cavern.',
    '',
    'Deep scratches cover the walls.',
    'The floor trembles beneath distant footsteps.',
    '',
    'PRESS ANY KEY',
  ],
  5: [
    'ENTERING LEVEL 5:',
    'THE DRAGON DEPTHS',
    '',
    'The air tastes of smoke, acid and decay.',
    '',
    'Scales as large as shields lie scattered',
    'across the floor.',
    '',
    'Something nearby exhales.',
    '',
    'PRESS ANY KEY',
  ],
  6: [
    'ENTERING LEVEL 6:',
    'THE SUNKEN ABYSS',
    '',
    'Black water runs between the stones.',
    '',
    'A voice speaks inside your mind, although',
    'you are certain you are alone.',
    '',
    'Far below, something ancient stirs.',
    '',
    'PRESS ANY KEY',
  ],
  7: [
    'ENTERING LEVEL 7:',
    'THE INFERNAL THRONE',
    '',
    'The ladder ends above a plain of black stone.',
    '',
    'The darkness is broken by rivers of fire.',
    'Monstrous shapes move beyond the flames.',
    '',
    'At the center of this level waits Asmodeus.',
    '',
    'PRESS ANY KEY',
  ],
};

export function getLevelIntro(levelNum: number): string[] {
  return LEVEL_INTROS[levelNum] ?? [`Entering Level ${levelNum}.`, '', 'PRESS ANY KEY'];
}
